# Generated by Django 4.1.7 on 2023-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Заказ в деталях",
                "verbose_name_plural": "Заказы в деталях",
            },
        ),
        migrations.AlterModelOptions(
            name="parameter",
            options={"verbose_name": "Параметр", "verbose_name_plural": "Параметры"},
        ),
        migrations.AlterModelOptions(
            name="productparameter",
            options={
                "verbose_name": "Параметр товара",
                "verbose_name_plural": "Параметры товара",
            },
        ),
        migrations.AlterModelOptions(
            name="productsinshop",
            options={
                "verbose_name": "Продукты в магазине",
                "verbose_name_plural": "Список продуктов в магазине",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "Магазин", "verbose_name_plural": "Магазины"},
        ),
        migrations.AlterField(
            model_name="shop",
            name="filename",
            field=models.CharField(max_length=50, null=True, verbose_name="Имя файла"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Эл.почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="third_name",
            field=models.CharField(max_length=50, verbose_name="Отчество"),
        ),
    ]
