# Generated by Django 4.1.7 on 2023-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_order", "0003_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True, default="-", max_length=40, verbose_name="Компания"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, default="-", max_length=40, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="third_name",
            field=models.CharField(default="-", max_length=50, verbose_name="Отчество"),
        ),
    ]
