# Generated by Django 4.1.7 on 2023-03-29 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend_order", "0004_alter_user_company_alter_user_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=40, verbose_name="Страна")),
                ("city", models.CharField(max_length=40, verbose_name="Город")),
                ("street", models.CharField(max_length=40, verbose_name="Город")),
                ("house", models.CharField(max_length=20, verbose_name="Дом")),
                ("building", models.CharField(max_length=20, verbose_name="Строение")),
                ("apartment", models.CharField(max_length=20, verbose_name="Квартира")),
                ("index", models.IntegerField(verbose_name="Индекс")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса пользователей",
            },
        ),
    ]
